language: objective-c
branches:
    only:
    - develop

env:
    global:
        - GH_USER="KtorZ"
        - secure: "NZ6JOTrBBZMZZMQe03zzyg7QUvXc6fUyCu8klNIIcOQ10dKbbEYbU73ryoD42VMd7TijyO+PRnHBw2ET3Ec4rFy2ZB6HZuXqjSVhFqjc0kBxDNHCHl8MDVUwbyvq5AABnKuniHQ1EfIzoDbVwN0zfKoLzOAKoJP2BhJLP0KwVVooBZ7ONs7tMrEl5lCe59dL7gPlwe3Ymp5f05hFec638gCzLu2oQIdUJNQ6r6bKPwoxWH5OZwRjTxFiJdYeqWk6xHusn4guZj54wVVYDekcpg7I6BddzXMWYadWftYVuqFkJaFToz4ZwlN5imG+Hfdo/BaTEnI3XZid0QVfh3w3J6IqB0C7zWgg4u5WQp3NxWq+ZU0OdY03H3g0bDN2w/l7EOkFblhamxpeQ1XGRQ/XrRD/PxDRSLQkb74y4Ih8/iEkS0kBPIdIXuGwHfVez82Rg+IbNSsShhwOePvUzhZ84t5gbDNS+xA8XfcHsbHPdfQWlUXSTJWSClp7lYP/jI3NVzTObhfr/qxXAW77lSxR/ezrssEkguUpVPQxtX7esfWwjPqcr2fG5Vj6LeS8lMMIo1ucqjOGyouBxqngiyD4sSgwoK6MDV1X33Imr0fJEedvNBwg6BIYB971Zw/4ZmXdMtCr3rNerm/bE7rnV+enu0qG6QNuNh+otPWlFkEr1F4="

script:
    - source deploy.sh
