language: objective-c
branches:
    only:
        - develop
env:
    matrix:
        - PLATFORM="ios"
        - PLATFORM="android" ANDROID_VERSION="19"
    global:
        - ANDROID_SDK_FILE="android-sdk_r24.3.4-macosx.zip" # From dl.google.com
        - ANDROID_HOME=${PWD}
        - ANDROID_SDK=${ANDROID_HOME}/android-sdk-macosx
        - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
#        - secure GENERATE_SECURE_TOKEN_FOR_CLOUDINARY

matrix:
    fast_finish: true
    allow_failures:
        - env: PLATFORM="android" ANDROID_VERSION="19"

install:
    - npm install -g titanium alloy
    - source install.sh

script:
    - titanium build -p ${PLATFORM} --build-only --log-level warn
