language: objective-c
branches:
    only:
    - develop

env:
    matrix:
        - PLATFORM="ios"
        - PLATFORM="android" ANDROID_VERSION="21"
    global:
        - ANDROID_SDK_FILE="android-sdk_r24.3.4-macosx.zip"
        - ANDROID_HOME=${PWD}
        - ANDROID_SDK=${ANDROID_HOME}/android-sdk-macosx
        - PATH=${PATH}:${ANDROID_SDK}/tools:${ANDROID_SDK}/platform-tools
        - GH_USER="TravisTheSmiths"
        - CI_REPO="https://raw.githubusercontent.com/TheSmiths/continuous-integration/master"
        - secure: "ySC7vCItH+1bS0gAmYz/iMewUTnTqG7WUzqX9vCi9DXw3idbWPqlhA5fCsL45fe3N9CtnsPQMFQFjhjCsy7Vd1lThE3iBg4HhojhpqjasTChMSzl9nHOKVw2GE9GKin6iKI4nhsbLeNsz1vO42h4Pxfav6zJ18hKNnm6pOvJwxV/sIgzFnT1HJzQdk3g1EftRz9CkiuN65dd5BI0Bx7eorFcygnE5dA3M1IsN7EHzV4c7I4HRafPxjwP4WVU6gzVwLOFxdSu7y7fammuuHTD/lbdtTEckbhT1+7kGeFeBtuYPbm2gVOx3tIo+uv9ZTUKZGzwEwILCDv//yqrYFK93muqJS7XeUFkyxClzxC57Elv2w8sqh3QwUOltKhA9b5hYSNlkDZteC8SEVOaF3VN7YL7SlUoYbkOO4Gc2npOjI7FD9ljHMzpFQCGRdRltrTgPjOZkVByOSEfd9hDwfzTbtKxy3fka9KGSQLUQM1wJP0YmvNYW2UFnRvHyB18WWrCiD/Z+5qngIwb7D5e0BWXUxlWfLzzOQhGgTMEf7+xYzw6smRZoerY3chsuZOxmeapvz7A/k3i1E8YLqfgeaVWtk28tLSkTTm8cUm6+PLVqJdqJuImGgKxBf2yzy8rDhwz2cVAyHzxaW4/JPEC7++p0hliXkAjHRI3JX8tklCjIPI="

matrix:
    fast_finish: true
    allow_failures:
        - env: PLATFORM="android" ANDROID_VERSION="21"

before_install:
    - curl -o install.sh ${CI_REPO}/install.sh
    - curl -o ignore.sh ${CI_REPO}/ignore.sh
    - curl -o release.sh ${CI_REPO}/release.sh
    - curl -o bump_version.sh ${CI_REPO}/bump_version.sh
    - chmod +x ignore.sh

install:
    - npm install -g titanium alloy
    - source install.sh

script:
    - source bump_version.sh app
    - titanium build -p ${PLATFORM} --build-only --log-level warn

after_success:
    - source release.sh
