language: objective-c
branches:
    only:
    - develop

env:
    global:
        - GH_USER="TravisTheSmiths"
        - secure: "1Slzgn4x+bJIvepdrznuM28GcwwjmUg2/lIi9nuedA+WhziSEgEW1NBecLC2TxH2V/VZnDQb6ikhPn8RzyoNgZW7S3B3Drcgjx2sCAadiwzFnrRIJBLY2A65PxZPEfEa25+88ROPfAmYlH94uRnpvchcc/NJJmRQO4VdlY0XFkanyU/PvvFb7y6YTqFtkRFqRQWaes3f59OgGd3bwKVONWdquDaTd4eUR6mg/wXrflo4MmTMhfB2T+8H0wrnankHBlu+hgwiNDM1jGsdbDPp44RvHpGQcXewruhn/jkE7ep5oAQ+2Caj7mHwqF0HeZoADUfZqgjkzGqfhqi542Q87KTM4aPH9H/dwpA5iZM6gkcSe5P3PUQ6DBgm4fDQiNCkydjGnhSKOmhrdGWL+Kl5hFtaKKUSoTAt5ND/RK+rwyvz2ZD6n1d5O8HL3nnsqC6dFStX96Y3oSwsLnyuU0siEcbJ8NonSU3NThdc4c8ISXG9jkwJa/jLXatGN2SrHuaUXVwcA4C4pAt+Adq5fW8keqCEMWXKQQvv8iNH4OkO3Rs+8kezG0gG7N5O+zpDK3gngk0pKghNQLVMSGMcnM4Zw6sLYBZxCSOEEAlpP0m3uWErO560Mk4mCsBrbYQuWrAZ48Ovl/+qaY2lsaCKEuPumNmjjopgI+7zcXbXZKQmbzg="

script:
    - source deploy.sh
